####################################################################
# PopulationSim Properties
####################################################################


# Algorithm/Software Configuration
# ------------------------------------------------------------------
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: True
USE_SIMUL_INTEGERIZER: True
USE_CVXPY: False
max_expansion_factor: 30


# Geographic Settings
# ------------------------------------------------------------------
#geographies: [PUMA, block_group]
#geographies: [state, county, PUMA, tract, block_group]
#geographies: [state, county, PUMA, block_group]
geographies: [region, PUMA, block_group_id]
seed_geography: PUMA


# Tracing
# ------------------------------------------------------------------
trace_geography:
  TAZ: 100
  TRACT: 10200

  
# Data Directory
# ------------------------------------------------------------------
data_dir: R:/SyntheticPopulation_2018/group_quarters/input_files


# Input Data Tables
# ------------------------------------------------------------------
# input_pre_processor input_table_list
input_table_list:
  - tablename: households
    filename : seed_households_gq.csv
    index_col: hh_id
    column_map:
      # not sure what SERIALNO is, but it is not unique
      #SERIALNO: hh_id
      hhnum: hh_id
  - tablename: persons
    # expression_filename: seed_persons_expressions.csv
    filename : seed_persons_gq.csv
    column_map:
      #SERIALNO: hh_id
      hhnum: hh_id
      #SPORDER: per_num
    # drop mixed type fields that appear to have been incorrectly generated
    #drop_columns:
    #  - indp02
    #  - naicsp02
    #  - occp02
    #  - socp00
    #  - occp10
    #  - socp10
    #  - indp07
    #  - naicsp07
  - tablename: geo_cross_walk
    filename : geo_cross_walk.csv
   # column_map:
   #   TRACTCE: TRACT
  - tablename: block_group_id_control_data
    filename : bg_gq_control_targets.csv
  #- tablename: TRACT_control_data
  #  filename : control_totals_tract.csv
  #- tablename: REGION_control_data
    #filename : control_totals_meta.csv
    #filename : scaled_control_totals_meta.csv


# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: weight_hh    # all households have a weight equal to the hhsize of 1
household_id_col: hh_id
total_hh_control: puma_tot_gq_hh


# Control Specification File Name
# ------------------------------------------------------------------
control_file_name: controls.csv


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
    - summary_block_group_id
    - expanded_household_ids


# Synthetic Population Output Specification
# ------------------------------------------------------------------
#

output_synthetic_population:
  household_id: household_id
  households:
    filename: synthetic_households.csv
    columns:
      - ADJINC
  persons:
    filename: synthetic_persons.csv
    columns:
      - SEX
      - AGE
      - PINCIP
      - ESR
      - SCH


# Steps for base mode
# ------------------------------------------------------------------
run_list:
  steps:
    - input_pre_processor
    - setup_data_structures
    - initial_seed_balancing
    - meta_control_factoring
    - final_seed_balancing
    - integerize_final_seed_weights
    - sub_balancing.geography=block_group_id
    - expand_households
    - summarize
    - write_tables
    - write_synthetic_population

  #resume_after: expand_households
